language: cpp
    
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package hadley/testthat
  - if [ "$RCPP" = "Rcpp" ]; then ./travis-tool.sh github_package RcppCore/Rcpp; fi
  - if [ "$RCPP" = "Rcpp11" ]; then ./travis-tool.sh github_package Rcpp11/Rcpp11; ./travis-tool.sh github_package Rcpp11/attributes; fi
 
script: 
  - R CMD INSTALL .
  - cd tests
  - Rscript testthat.R

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - RCPP=Rcpp
  - RCPP=Rcpp11
