language: r
sudo: false
cache: packages
warnings_are_errors: true
latex: false
dist: trusty

matrix:
  include:
    - os: linux
      r: release
      addons:
        apt:
          packages:
            - valgrind
      r_check_args: '--as-cran --use-valgrind'
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
      r_github_packages:
        - jimhester/covr
      after_success:
        - Rscript -e 'covr::codecov()'

    - os: linux
      compiler: clang
      r: release

    - os: linux
      r: devel
      compiler: clang

    - os: linux
      r: devel
      compiler: gcc

    - os: linux
      r: oldrel
      compiler: clang

    - os: linux
      r: oldrel
      compiler: gcc

    - os: osx
      r: release

    - os: osx
      r: oldrel

notifications:
  email:
    on_success: change
    on_failure: change