language: r
sudo: false
cache: packages
warnings_are_errors: true
latex: false

matrix:
  include:
    - os: linux
      compiler: gcc
      r: release
      addons:
        apt:
          packages:
            - valgrind
      r_check_args: '--as-cran --use-valgrind'
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
        
    - os: linux
      compiler: clang
      r: release

    - os: linux
      compiler: gcc
      r: devel

    - os: linux
      compiler: clang
      r: devel

    - os: linux
      compiler: gcc
      r: oldrel

    - os: linux
      compiler: clang
      r: oldrel

    - os: osx
      r: release

    - os: osx
      r: oldrel

notifications:
  email:
    on_success: change
    on_failure: change